Codefriar/crud fls updates
trailheadapps/dreamhouse-sfdx pull request #102
Opened 2022-01-24 16:59 UTC by codefriar

@pozil - This PR is at the request of @ccoenraets, who's cc'd for visibility. This PR does two main things:

1. it brings Prettier, and npm scripts to the *old* dreamhouse-sfdx project. 
   * The Pretterrc and prettier ignore files have been pulled from apex-recipes. 
   * .gitIgnore has been copied from apex-recipes
   * package.json has been copied from, and modified from dreamhouse-lwc
2. It brings requested security updates discovered by the CLI scanner team. Specifically: 
   * All queries now utilize 'WITH SECURITY_ENFORCED'
   * SampleDataController has been refactored with a guard pattern to fail-fast if the executing user does not have proper CRUD permissions to the necessary objects. It's also been refactored to reduce complexity and adhere to best-practices.

2022-01-24 19:11 UTC, pozil requested changes
@codefriar I found a few queries that might require FLS enforcement, can you double check?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/triggers/RejectDuplicatePropertyFavorite.trigger
> +    ];
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerMyOpenCases.cls
> +            WHERE OwnerId = :UserInfo.getUserId() AND Status != 'Closed'
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerNext.cls
> +            LIMIT 1
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerNext.cls
> +                AND Status != 'Closed'
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerReport.cls
> +            LIMIT 5
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerSOQL.cls
>          SObject[] objects = Database.query(utterance);
We need to figure out what goes in here and enforce FLS.

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/HandlerTopOpportunities.cls
> +            LIMIT :qty
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/PostPriceChangeToSlack.cls
> +            WHERE Id = :propId
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/PushPriceChangeNotification.cls
> +            WHERE Id = :propId
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/PushPriceChangeNotification.cls
> +            WHERE property__c = :propId
Enforce FLS?

2022-01-24 19:11 UTC, pozil commented on force-app/main/default/classes/SlackOpportunityPublisher.cls
> +            WHERE Id = :oppId
Enforce FLS?

2022-01-24 19:38 UTC, codefriar commented on force-app/main/default/classes/PropertyController.cls
> +        ];
Not in this case. In this case, it's a COUNT() query.

2022-01-24 19:39 UTC, codefriar commented on force-app/main/default/classes/EinsteinVisionController.cls
> +                LIMIT 1
This was not one of the queries the CLI scanner identified. Investigating.

2022-01-24 22:03 UTC, codefriar commented on force-app/main/default/classes/EinsteinVisionController.cls
> +                LIMIT 1
@pozil - While i'd initially gone through this based on the report the cli scanner team sent - and thus overlooked this one - it turns out querying contentVersion with 'WITH SECURITY_ENFORCED' enabled, throws an error - it's not allowed on contentVersion.

2022-01-24 22:04 UTC, codefriar commented on force-app/main/default/classes/HandlerDashboard.cls
> +            LIMIT 5
With Security enforced is not allowed on Dashboard.

2022-01-24 22:06 UTC, codefriar commented on force-app/main/default/classes/HandlerFileUpload.cls
> +                WHERE LatestPublishedVersionId = :v.Id
Doesn't apply because the lastPublishedVersionId is a contentVersion id and contentVersion can't use WITH SECURITY_ENFORCED

2022-01-24 22:07 UTC, codefriar commented on force-app/main/default/classes/HandlerFindAccount.cls
> +            LIMIT 5
Good catch. I don't know why the cli scanner team didn't pick this up.

2022-01-24 22:20 UTC, codefriar commented
@pozil - I did a scan of other queries and pulled my own PMD report locally. I've addressed other queries where WITH SECURITY_ENFORCED makes sense, but there is an entire rabbit hole of other issues here to address. For now, unless this project is re-activated, I'd like to call it done having addressed the issues the CLI scanner team identified.

2022-01-25 10:11 UTC, pozil commented
Got it, good to merge then.

2022-01-25 10:12 UTC, pozil approved these changes

2022-01-25 19:52 UTC, merged